// <auto-generated />
namespace BudgetControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddfieldstatustoTransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddfieldstatustoTransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201703041905455_Add field status to Transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
