// <auto-generated />
namespace BudgetControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCurrentWorkingCC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCurrentWorkingCC));
        
        string IMigrationMetadata.Id
        {
            get { return "201807030814274_AddCurrentWorkingCC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
